name: my-first-nest
# 用于启动数据库容器
services:
  postgres:
    image: postgres:17
    container_name: my-first-nest-db
    restart: on-failure:5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: first-nest
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - my-nest-network

networks:
  my-nest-network:
    external: true
    name: my-nest-network

volumes:
  pg-data:
