name: my-first-nest
# 用于构建镜像并启动容器
services:
  app:
    container_name: my-first-nest-app
    build:
      context: ..
      dockerfile: Dockerfile
    image: my-first-nest:latest
    ports:
      - '3000:80'
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/first-nest
      DEFAULT_ADMIN_USERNAME: admin
      DEFAULT_ADMIN_PASSWORD: admin1234
      JWT_SECRET: my-first-nest-jwt-secret
      # 若同时启动了 docker-compose.cache.yml，会通过 my-nest-network 解析到 redis 服务
      REDIS_URL: redis://redis:6379
      REDIS_REQUIRED: 'false'
    restart: on-failure:5
    networks:
      - my-nest-network

networks:
  my-nest-network:
    external: true
    name: my-nest-network
