name: my-first-nest
# 用于启动已经构建好的镜像
services:
  app:
    container_name: my-first-nest-app-local
    image: my-first-nest:latest
    restart: on-failure:5
    ports:
      - '3000:80'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/first-nest
      DEFAULT_ADMIN_USERNAME: admin
      DEFAULT_ADMIN_PASSWORD: admin1234
      JWT_SECRET: my-first-nest-jwt-secret
    networks:
      - my-nest-network

networks:
  my-nest-network:
    external: true
    name: my-nest-network
